### ISSUE TITLE
Use of unknown class

### ISSUE THREAD

**Issue by ksn135** [DEVSENSE/php4vs#1]
Greetings gentlemen! Great product! 
However, it is very annoying to get bogus messages about unknown classes, especially if they are declared correctly above.
Maybe I'm doing something wrong?
```v1.30.12518```
<img width="1494" alt="Screenshot 2023-02-15 at 11 58 12" src="https://user-images.githubusercontent.com/230304/218980888-7aefc948-b6da-435e-879d-76bb3b27055d.png">
<img width="2167" alt="Screenshot 2023-02-15 at 11 58 46" src="https://user-images.githubusercontent.com/230304/218980982-424a9ff6-25ef-4645-a0f1-9eb5c23ab6dc.png">

**Comment by ksn135** [comment]
related https://github.com/DEVSENSE/phptools-docs/issues/284

**Comment by jakubmisek** [comment]
thank you for pointing this out - we'll continue tracking it on https://github.com/DEVSENSE/phptools-docs/issues/284
