### ISSUE TITLE
VSCode WSL2 project storing cache in a windows path directory

### ISSUE THREAD

**Issue by savemetenminutes** [DEVSENSE/php4vs#2]
I've recently installed the trial version of Devsense PHP for Visual Studio Code, so I'm sort of an aspiring new user and potential long-time customer of your software. I'm considering moving away from PHPStorm and still getting used to the features of PHP for VSCode. This is the first issue I've ever reported on your issue tracker. That being said I'm not even sure this is the correct repo the issue should be reported to as I'm not sure if this repo is related to both Visual Studio and Visual Studio Code or if the issue manifests within Visual Studio as I'm only using the PHP for VSCode extension.

Another disclaimer is that I'm not 100% sure if this issue is caused specifically by the PHP for VSCode extension, by any of the other Devsense extension or by another vendor extension altogether, but I've verified that the issue does not manifest whenever I disable all extensions within VSCode. The reason I think it's related to PHP for VSCode is two-fold. I started experiencing the issue around the time I installed the trial version of PHP for VSCode. The other reason will be explained as part of the issue description, so let's get to it already!

First of all the setup:
VSCode:
```
Version: 1.92.2 (user setup)
Commit: fee1edb8d6d72a0ddff41e5f71a671c23ed924b9
Date: 2024-08-14T17:29:30.058Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.19045
```

PHP for VSCode (free trial):
`1.50.15906 (August 20, 2024)`

The project is running in a WSL2 window with only one content root directory added, the path being:
`/home/work/adex-docker/volumes-common/directory/var/www/content/adex-sales`

The actual issue is that (most likely) the PHP for VSCode extension uses the windows path for VSCode cache instead of a WSL2 path. This results in a new directory, which is created inside the content root, which is named exactly like the VSCode cache directory would be under a project running in a Windows window (non-WSL2). So the full path to the problematic directory is:
`/home/work/adex-docker/volumes-common/directory/var/www/content/adex-sales/"D:\VSCode\Cache"`

Obviously the WSL2 subsystem cannot resolve the absolute Windows path D:\VSCode\Cache and created a similarly named directory within the project root directory, which resides on the WSL2 partition. I don't even know why the cache directory refers to the `D:` drive as VSCode is installed under `C:`. This directory is both visible inside the explorer sidebar of the project and when I type `ls` inside the terminal. I can open and browse the directory and it contains what appears to be a matching directory structure to the vendor directory of the adex-sales superproject, which uses Composer for package management. Inside each vendor subdirectory there are .json.gz files, which correspond to the package names and their versions, so the file name template is of the format {package-name}.{version}.json.gz. So for example there is a file corresponding to the doctrine/orm package at:
`/home/work/adex-docker/volumes-common/directory/var/www/content/adex-sales/"D:\VSCode\Cache"/doctrine/orm.3.2.2.json.gz`

Here's a snippet from the file when I un-gzip it:
`{"nodes_v":9,"f":[],"c":[],"t":[{"m":[{"h":"string","n":"AbstractSchemaName","d":{"en":"AbstractSchemaName ::= fully_qualified_name | identifier"},"u":"#845"},{"p":[{"n":"className","t":"(class-string<Doctrine\\ORM\\Query\\TreeWalker>)","h":"string"}],"h":"void","n":"addCustomTreeWalker","d":{"en":"Adds a custom tree walker for modifying the AST."},"u":"#185"},{"h":"Doctrine\\ORM\\Query\\AST\\AggregateExpression","n":"AggregateExpression","d":{"en":"AggregateExpression ::=\n(\"AVG\" | \"MAX\" | \"MIN\" | \"SUM\" | \"COUNT\") \"(\" [\"DISTINCT\"] SimpleArithmeticExpression \")\""},"u":"#2717"},{"h":"string","n":"AliasIdentificationVariable","d":{"en":"AliasIdentificationVariable = identifier"},"u":"#824"},{"h":"string","n":"AliasResultVariable","d":{"en":"AliasResultVariable ::= identifier"},"u":"#881"},{"h":"Doctrine\\ORM\\Query\\AST\\ArithmeticExpression","n":"ArithmeticExpression","d":{"en":"ArithmeticExpression ::= SimpleArithmeticExpression | \"(\" Subselect \")\""},"u":"#2451"},{"t":"Doctrine\\ORM\\Query\\AST\\ArithmeticFactor|Doctrine\\ORM\\Query\\AST\\Node|string","h":"Doctrine\\ORM\\Query\\AST\\Node|string|Doctrine\\ORM\\Query\\AST\\ArithmeticFactor","n":"ArithmeticFactor","d":{"en":"ArithmeticFactor ::= [(\"+\" | \"-\")] ArithmeticPrimary"},"u":"#2526"},{"h":"Doctrine\\ORM\\Query\\AST\\Node|string","n":"ArithmeticPrimary","d":{"en":"ArithmeticPrimary ::= SingleValuedPathExpression | Literal | ParenthesisExpression\n| FunctionsReturningNumerics | AggregateExpression | FunctionsReturningStrings\n| FunctionsReturningDatetime | IdentificationVariable | ResultVariable\n| InputParameter | CaseExpression"},"u":"#2553"},{"h":"Doctrine\\ORM\\Query\\AST\\Node|string","n":"ArithmeticTerm","d":{"en":"ArithmeticTerm ::= ArithmeticFactor {(\"*\" | \"/\") ArithmeticFactor}*"},"u":"#2501"},{"h":"Doctrine\\ORM\\Query\\AST\\PathExpression","n":"AssociationPathExpression","d":{"en":"AssociationPathExpression ::= CollectionValuedPathExpression | SingleValuedAssociationPathExpression"},"u":"#991"},{"h":"Doctrine\\ORM\\Query\\AST\\BetweenExpression","n":"BetweenExpression","d":{"en":"BetweenExpression ::= ArithmeticExpression [\"NOT\"] \"BETWEEN\" ArithmeticExpression \"AND\" ArithmeticExpression"},"u":"#2771"},{"h":"mixed","r":{"en":"One of the possible expressions or subexpressions."},"n":"CaseExpression","d":{"en":"CaseExpression ::= GeneralCaseExpression | SimpleCaseExpression | CoalesceExpression | NullifExpression\nGeneralCaseExpression ::= \"CASE\" WhenClause {WhenClause}* \"ELSE\" ScalarExpression \"END\"\nWhenClause ::= \"WHEN\" ConditionalExpression \"THEN\" ScalarExpression\nSimpleCaseExpression ::= \"CASE\" CaseOperand SimpleWhenClause {SimpleWhenClause}* \"ELSE\" ScalarExpression \"END\"\nCaseOperand ::= StateFieldPathExpression | TypeDiscriminator\nSimpleWhenClause ::= \"WHEN\" ScalarExpression \"THEN\" ScalarExpression\nCoalesceExpression ::= \"COALESCE\" \"(\" ScalarExpression {\",\" ScalarExpression}* \")\"\nNullifExpression ::= \"NULLIF\" \"(\" ScalarExpression \",\" ScalarExpression \")\""},"u":"#1780"},{"h":"Doctrine\\ORM\\Query\\AST\\CoalesceExpression","n":"CoalesceExpression","d":{"en":"CoalesceExpression ::= \"COALESCE\" \"(\" ScalarExpression {\",\" ScalarExpression}* \")\""},"u":"#1814"},{"h":"Doctrine\\ORM\\Query\\AST\\CollectionMemberExpression","n":"CollectionMemberExpression","d":{"en":"CollectionMemberExpression ::= EntityExpression [\"NOT\"] \"MEMBER\" [\"OF\"] CollectionValuedPathExpression\n\nEntityExpression ::= SingleValuedAssociationPathExpression | SimpleEntityExpression\nSimpleEntityExpression ::= IdentificationVariable | InputParameter"},"u":"#2366"},{"h":"Doctrine\\ORM\\Query\\AST\\PathExpression","n":"CollectionValuedPathExpression","d":{"en":"CollectionValuedPathExpression ::= IdentificationVariable \".\" CollectionValuedAssociationField"},"u":"#1029"},{"h":"Doctrine\\ORM\\Query\\AST\\ComparisonExpression","n":"ComparisonExpression","d":{"en":"ComparisonExpression ::= ArithmeticExpression ComparisonOperator ( QuantifiedExpression | ArithmeticExpression )"},"u":"#2792"},{"h":"string","n":"ComparisonOperator","d":{"en":"ComparisonOperator ::= \"=\" | \"<\" | \"<=\" | \"<>\" | \">\" | \">=\" | \"!=\""},"u":"#3046"},{"h":"Doctrine\\ORM\\Query\\AST\\ConditionalExpression|Doctrine\\ORM\\Query\\AST\\ConditionalFactor|Doctrine\\ORM\\Query\\AST\\ConditionalPrimary|Doctrine\\ORM\\Query\\AST\\ConditionalTerm","n":"ConditionalExpression","d":{"en":"ConditionalExpression ::= ConditionalTerm {\"OR\" ConditionalTerm}*"},"u":"#2128"},{"h":"Doctrine\\ORM\\Query\\AST\\ConditionalFactor|Doctrine\\ORM\\Query\\AST\\ConditionalPrimary","n":"ConditionalFactor","d":{"en":"ConditionalFactor ::= [\"NOT\"] ConditionalPrimary"},"u":"#2174"},{"h":"Doctrine\\ORM\\Query\\AST\\ConditionalPrimary","n":"ConditionalPrimary","d":{"en":"ConditionalPrimary ::= SimpleConditionalExpression | \"(\" ConditionalExpression \")\""},"u":"#2198"},{"h":"Doctrine\\ORM\\Query\\AST\\ConditionalFactor|Doctrine\\ORM\\Query\\AST\\ConditionalPrimary|Doctrine\\ORM\\Query\\AST\\ConditionalTerm","n":"ConditionalTerm","d":{"en":"ConditionalTerm ::= ConditionalFactor {\"AND\" ConditionalFactor}*"},"u":"#2151"},{"h":"Doctrine\\ORM\\Query\\AST\\Functions\\FunctionNode","n":"CustomFunctionsReturningDatetime","u":"#3203"},{"h":"Doctrine\\ORM\\Query\\AST\\Functions\\FunctionNode","n":"CustomFunctionsReturningNumerics","u":"#3165"},{"h":"Doctrine\\ORM\\Query\\AST\\Functions\\FunctionNode","n":"CustomFunctionsReturningStrings","u":"#3242"},{"h":"Doctrine\\ORM\\Query\\AST\\DeleteClause",`

I hope this sums up the issue in a good enough detail. I'm happy to provide further info as needed.

**Comment by jakubmisek** [comment]
Thank you very much for trying our tools, and for reporting the issue in detail. 

The file is from our extension, although the path is not :/ we're caching the packages in `/DEVSENSE/packages-cache/` within WSL's user folder.

I have no idea where D:\VSCode\Cache comes from. Are there any other files?

**Comment by jakubmisek** [comment]
@savemetenminutes May I ask you to check the setting:

`php.cache.location` - do you have anything set to this setting?

**Comment by savemetenminutes** [comment]
Spot on! I do have this line in the user settings.
```
    "php.cache.location": "D:\\VSCode\\Cache",
```
Is it possible to disable it only for projects opened in the WSL subsystem?

On an unrelated note I wanted to ask you if it is possible to find all the usages of a specific class method using PHP for VSCode. I've tried (right click on the method name in the editor) the `Go to implementations`,  `Go to references` , `Find all references`, `Find all implementations`, `Peek->Peek implementations`, `Peek->Peek references` context menu options and non of them provides a credible list of references/usages of the method across the indexed code base.

Another question is whether a single VSCode Xdebug remote debugger session can be terminated without actually having to restart the debugger listener each time as it makes step-by-step debugging very clumsy otherwise.

**Comment by jakubmisek** [comment]
I'm glad it worked!

> Is it possible to disable it only for projects opened in the WSL subsystem?

I'll definitely add some checks on whether the path makes sense. However, please set the WSL-specific setting using the steps described at https://code.visualstudio.com/docs/remote/wsl#_wsl-specific-settings. You can specify `"php.cache.location": null` so it falls back to the default behavior.

> On an unrelated note I wanted to ask you if it is possible to find all the usages of a specific class method

`Go to references` is the correct way. We may miss some usages if the editor does not analyze the code properly - I would like to ask for more specific test cases where we don't recognize the reference properly, and we'll try to improve in future updates.

> Another question is whether a single VSCode Xdebug remote debugger session can be terminated without actually having to restart the debugger listener each time as it makes step-by-step debugging very clumsy otherwise.

I would suggest configuring your launch profile to listen for an Xdebug connection (https://docs.devsense.com/en/vscode/debug/launch-json#listen-for-xdebug-locally-or-remote-debug). Don't stop the session (Shift+F5 or red stop button) - the Xdebug debugger will keep listening and you don't need to restart it.

**Comment by savemetenminutes** [comment]
I've set
```
{
    "php.cache.location": null,
```
in `/root/.vscode-server/data/Machine`. It's complaining about `Incorrect type. Expected "string".`, but so far I haven't encountered the erroneous directory, but I don't see a /DEVSENSE directory on my WSL2 Debian partition either.

Does `Go to references` check for usages in the vendor directory? My project structure is fully modular and my main app logic is also part of a composer package. I don't keep any logic within the superproject.

I have configured my launch profile properly and successfully running Xdebug sessions. However, I don't see any way of terminating an active session prematurely (without completing the whole script run). The only way I'm able to do it is to hit the red square button or Shift+F5, but like you pointed out this stops the listener as well and this is the source of the whole problem.

**Comment by jakubmisek** [comment]
Thanks for pointing this out, `null` will be fixed.

`go to references` does not check the release packages in `vendor` folder; We should be able to recognize packages that are being developed (they are softlinks or their version is `dev`) but otherwise we try to hide everything in them from user.

Yes, Shift+F5 kills the debug session. I'm not aware of any command that would just finish the current request and keep listening. I may create a new issue for this one.

**Comment by savemetenminutes** [comment]
```
We should be able to recognize packages that are being developed (they are softlinks or their version is dev) 
```

This is mostly never the case with our projects. In our service-specific business logic package we have a default dev branch (say 3.x-dev), which we branch feature branches off of, which later get merged back to. Then a new tag/version is incremented and composer update checks out the commit hash of the tag. The composer.json has a ex. ~3.1.0 version constraint on the app project package. Then we also have a bunch of core packages with some 3rd party service integration or SDK abstraction, which are shared inbetween different microservices and inbetween different projects altogether. They follow pretty much the same git/composer update flow. We almost never use dev- branch-based constraints in composer.json even for local development purposes. For purposes of easy refactoring, finding references of say the base method of an extending class would then be able to check for core package usages as well, which would most of the time be checked out to commit hashes. Some setting to be able to include all vendor packages for 'Go to references' and right-click refactor rename namespace/class/method/property/constant across all usages would be quite helpful.

**Comment by jakubmisek** [comment]
I see, thank you for the detailed description.

We will work on it; just for you to know, as a result, it will consume more RAM.

**Comment by savemetenminutes** [comment]
That's totally fine and understandable. VSCode still outperforms the other competitors by a large margin. Currently I'm having a hard time feeding PHPStorm's JVM enough RAM for its indexing with 28GB dedicated just for the IDE alone. AFAIK VSCode runs on the Electron framework, which should be way slower than a native Win32 app or whatever it's called nowadays, or even something written in JAVA, but somehow you don't get the 5-15 minutes of (re)indexing (with a pretty decent CPU and SSD) PHPStorm needs just when you launch the app and every once in awhile afterwards.

**Comment by jakubmisek** [comment]
Interesting! Also even though VSCode is in Electron, our extension for example is native code running out-of-process. We try to optimize indexing and memory use as much as possible.

**Comment by savemetenminutes** [comment]
I would assume part of the reason for the slow indexing in PHPStorm is that they don't have a fully integrated WSL file watcher the way that VSCode projects running in a WSL window do, so what they do is they reindex the whole content directory whenever new files are detected through a recursive refresh of the whole directory, which to make matters even worse is not really controllable and triggerable on-demand, but as I have reported happens seemingly at random, although I have found a workaround to be able to trigger it myself.

On a side note I was wondering whether uninstalling the trial version of PHP for VSCode until the changes are implemented will in a sense pause the trial so I can still test the necessary functionality before buying the full version license.
